# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loli < Formula
  desc "Install Loli CLI with brew and find animes passing images"
  homepage "https://github.com/ci-monk/loli"
  version "1.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ci-monk/loli/releases/download/v1.15.0/loli_v1.15.0_Darwin-x86_64.tar.gz"
      sha256 "0a2ea4c5b44a63845eeb62abcd1f7d4b9b061c76f7a1fe9dfa72d6a95fb658b0"

      def install
        bin.install "loli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ci-monk/loli/releases/download/v1.15.0/loli_v1.15.0_Darwin-arm64.tar.gz"
      sha256 "143736a1995f7e8776eeb3b02be69017b636941fc20258fcc450f1aa7409a53f"

      def install
        bin.install "loli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ci-monk/loli/releases/download/v1.15.0/loli_v1.15.0_Linux-arm64.tar.gz"
      sha256 "91fc3940463c62b026d3ef12c180da7bfbd60fea763a5d434a960b330f4ab5d2"

      def install
        bin.install "loli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ci-monk/loli/releases/download/v1.15.0/loli_v1.15.0_Linux-x86_64.tar.gz"
      sha256 "f78ce452c677b3c099730b484b7402793758178644eb296e368c132b51969dde"

      def install
        bin.install "loli"
      end
    end
  end
end
