# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loli < Formula
  desc ""
  homepage "https://github.com/ci-monk/loli"
  version "1.12.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ci-monk/loli/releases/download/v1.12.7/loli_v1.12.7_Darwin-arm64.tar.gz"
      sha256 "5585a7bbd7d9ef05b4f3cced1802e8b4f0223efd0d11fb75f29cf2200549600b"

      def install
        bin.install "loli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ci-monk/loli/releases/download/v1.12.7/loli_v1.12.7_Darwin-x86_64.tar.gz"
      sha256 "82ee7601aa7aa94ce3e4b3130a2df12f054e49adbef0841f82382a31a4bf1a5d"

      def install
        bin.install "loli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ci-monk/loli/releases/download/v1.12.7/loli_v1.12.7_Linux-arm64.tar.gz"
      sha256 "034c6ebcc653aa0190f4b999f1d5e5b2019fd9658836eea11f0bfd61c22ca8c9"

      def install
        bin.install "loli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ci-monk/loli/releases/download/v1.12.7/loli_v1.12.7_Linux-x86_64.tar.gz"
      sha256 "da3f77cc4567cef08198eba699b0eab61ae7ab0194cfffc0f1dc5e7a69acaae6"

      def install
        bin.install "loli"
      end
    end
  end
end
